### PR TITLE
make parameter 'uplo' optional for [c]tricpy

### PR DESCRIPTION
**Pull request by jo-37**
Enable calling `$m->tricpy()` to extract an upper triangular matrix as discussed at [PerlMonks](https://perlmonks.org/index.pl?node_id=11157483)

This change will silently break code like
```
sequence(3,3,2)->tricpy(indx(1, 0))
```

### CODE REVIEW

**Review by mohawk2 — CHANGES_REQUESTED** [review]
Thank you for this! It will break the code as you say, but I don't think there's much risk. I've done a quick search on grep.metacpan.org anyway.

Please could you make a couple of changes?
- make the `Doc` be `<<'EOT'` and get rid of the `\`
- not document `ctricpy` at all
- update the tests to have hardcoded (maybe 3x3) values - you're literally using `tricpy` to test a version of `tricpy`, which is pointless

**Comment by jo-37** [comment]
Thanks for your review and your suggestions, fixed so far. However, I'm not sure what you mean with *"not document `ctricpy` at all"*. Shall I completely remove its POD entry?

**Comment by mohawk2** [comment]
> Thanks for your review and your suggestions, fixed so far. However, I'm not sure what you mean with _"not document `ctricpy` at all"_. Shall I completely remove its POD entry?

Yes please. As alluded on PerlMonks, anything that helps PDL::Complex is "legacy" and shouldn't be visibly supported (even though I'm not going to delete it just yet, and even if your nice new feature does quite rightly also apply to this legacy code).

**Comment by jo-37** [comment]
Moved the doc from POD to comment.

**Comment by mohawk2** [comment]
It's fortunate that you did that, because it caused me to notice that you've put `=for exampleS`, not `=for example`. Sorry I missed that before. Please can you make it be spelled right for `tricpy`? You know how dang fussy computers can be.

I did ask you to remove the docs for `ctricpy`. Putting extra comments in the file makes for extra text that the maintainer (which is me) needs to mentally process whenever they need to make a change/read the code. If you would like to become the maintainer of this distro, go ahead and contribute a number of other things to it to the point that the PDL community has confidence you'll add value doing so. At that point, you can add as many comments as you like! Until then, please make the current maintainer's life easier by removing those comments.

**Comment by jo-37** [comment]
Removed the comment and fixed the format.

**Comment by mohawk2** [comment]
Thank you for your excellent contribution! Released as 0.38.

**Pull request merged**
