### PR TITLE
Old things

### PR DESCRIPTION
**Pull request by gvanuxem**

### CODE REVIEW

**Comment by mohawk2** [comment]
Thanks - your 2 real commits are great and I'm about to merge them.

However, you added a merge-commit from the current main-repo `master` which made GH think all was equal and therefore there were no diffs, which I am certain is not what you intended. I have force-pushed to your branch removing that merge-commit.

**Comment by mohawk2** [comment]
I did a "rebase" merge which did nothing, because these two commits were already on `master`, because you already PR-ed them in #13.

**Comment by gvanuxem** [comment]
Yes, I supposed that too. But they were pending in my repository. For
an unknown reason. So I pulled them just in case.
Sorry for the inconvenience.

**Comment by mohawk2** [comment]
That's Ok. The way to check this sort of thing would be to rebase the branch you're using (which should never be `master`) against the main `master`, and see if any conflicts happen or commits remain. If none remain, there's no action needed :-)

**Comment by gvanuxem** [comment]
Hello,

And happy new year. Thanks for the return. I think I will delete my PDL-
LinearAlgebra repository and re-fork it. I have nothing pending for it so
it’s not a problem. However I have some for the NonLinear-Optimization
module. They are not pushed in my repository to pull a request, that stil
requires substantial work since I saw that several routines need to be
updated to reflect thé actual implementation.

Regards,

__
Greg

**Comment by mohawk2** [comment]
Happy New Year!

Deleting and reforking is OK, of course, but I found the effort of understanding git well enough to not need to has paid me back hundreds of times. Up to you :-)

For the NonLinear stuff, I look forward to seeing your results!

**Pull request merged**
